import { MappingTypeMapping } from '@elastic/elasticsearch/api/types';
const mappings = {
	properties: {
		mutation_id: { type: 'keyword' },
		reference_genome_assembly: { type: 'keyword' },
		genomic_dna_change: { type: 'keyword' },
		chromosome: { type: 'keyword' },
		start_position: { type: 'integer' },
		reference_allele: { type: 'keyword' },
		tumor_allele: { type: 'keyword' },
		variant_class: { type: 'keyword' },
		annotation: {
			type: 'nested',
			properties: {
				aa_change: { type: 'keyword' },
				amino_acids_reference: { type: 'keyword' },
				amino_acids_variant: { type: 'keyword' },
				biotype: { type: 'keyword' },
				canonical: { type: 'boolean' },
				ccds: { type: 'keyword' },
				cdna_position: { type: 'keyword' },
				cdna_length: { type: 'keyword' },
				cds_position: { type: 'keyword' },
				cds_length: { type: 'keyword' },
				clin_sig: { type: 'keyword' },
				coding_dna_change: { type: 'keyword' },
				codons_reference: { type: 'keyword' },
				codons_variant: { type: 'keyword' },
				consequence: { type: 'keyword' },
				cosmic: { type: 'keyword' },
				dbsnp: { type: 'keyword' },
				domains: { type: 'keyword' },
				ensembl_gene_id: { type: 'keyword' },
				ensembl_feature_id: { type: 'keyword' },
				exon_rank: { type: 'integer' },
				exon_total: { type: 'integer' },
				feature_type: { type: 'keyword' },
				feature_strand: { type: 'keyword' },
				gene_pheno: { type: 'integer' },
				gene_symbol: { type: 'keyword' },
				hgvsc: { type: 'keyword' },
				hgvsp: { type: 'keyword' },
				high_inf_pos: { type: 'keyword' },
				intron_rank: { type: 'integer' },
				intron_total: { type: 'integer' },
				mane_plus_clinical: { type: 'keyword' },
				mane_select: { type: 'keyword' },
				motif_name: { type: 'keyword' },
				motif_pos: { type: 'integer' },
				motif_score_change: { type: 'float' },
				polyphen_impact: { type: 'keyword' },
				polyphen_score: { type: 'float' },
				protein_position: { type: 'integer' },
				protein_length: { type: 'integer' },
				pubmed: { type: 'keyword' },
				sift_impact: { type: 'keyword' },
				sift_score: { type: 'integer' },
				transcription_factors: { type: 'keyword' },
				uniparc: { type: 'keyword' },
				uniprotkb_swissprot: { type: 'keyword' },
				uniprotkb_trembl: { type: 'keyword' },
				vep_impact: { type: 'keyword' },
			},
		},
		frequency: {
			properties: {
				thousand_genomes: {
					properties: {
						af: { type: 'keyword' },
						afr_af: { type: 'keyword' },
						amr_af: { type: 'keyword' },
						eas_af: { type: 'keyword' },
						eur_af: { type: 'keyword' },
						sas_af: { type: 'keyword' },
					},
				},
				esp: {
					properties: {
						aa_af: { type: 'keyword' },
						ea_af: { type: 'keyword' },
					},
				},
				gnomad_exomes: {
					properties: {
						af: { type: 'keyword' },
						afr_af: { type: 'keyword' },
						amr_af: { type: 'keyword' },
						asj_af: { type: 'keyword' },
						eas_af: { type: 'keyword' },
						fin_af: { type: 'keyword' },
						nfe_af: { type: 'keyword' },
						oth_af: { type: 'keyword' },
						sas_af: { type: 'keyword' },
					},
				},
				max_af: { type: 'keyword' },
				max_af_pop: { type: 'keyword' },
			},
		},
		occurrence: {
			type: 'nested',
			properties: {
				submitter_donor_id: { type: 'keyword' },
				gender: { type: 'keyword' },
				primary_site: { type: 'keyword' },
				vital_status: { type: 'keyword' },
				survival_time: { type: 'keyword' },
				cause_of_death: { type: 'keyword' },
				primary_diagnosis: {
					type: 'nested',
					properties: {
						submitter_primary_diagnosis_id: { type: 'keyword' },
						age_at_diagnosis: { type: 'keyword' },
						cancer_type_code: { type: 'keyword' },
						clinical_tumour_staging_system: { type: 'keyword' },
						clinical_stage_group: { type: 'keyword' },
						lymph_nodes_examined_status: { type: 'keyword' },
						performance_status: { type: 'keyword' },
						laterality: { type: 'keyword' },
						treatment: {
							type: 'nested',
							properties: {
								submitter_treatment_id: { type: 'keyword' },
								treatment_type: { type: 'keyword' },
								treatment_intent: { type: 'keyword' },
								treatment_start_interval: { type: 'keyword' },
								treatment_duration: { type: 'keyword' },
								response_to_treatment: { type: 'keyword' },
								chemotherapy: {
									type: 'nested',
									properties: {
										drug_name: { type: 'keyword' },
										drug_rxnormcui: { type: 'keyword' },
										cumulative_drug_dosage: { type: 'integer' },
										chemotherapy_dosage_units: { type: 'keyword' },
									},
								},
							},
						},
						follow_up: {
							type: 'nested',
							properties: {
								submitter_follow_up_id: { type: 'keyword' },
								interval_of_followup: { type: 'keyword' },
								disease_status_at_followup: { type: 'keyword' },
								relapse_type: { type: 'keyword' },
								submitter_treatment_id: { type: 'keyword' },
							},
						},
					},
				},
				comorbidity: {
					type: 'nested',
					properties: {
						age_at_comorbidity_diagnosis: { type: 'keyword' },
						comorbidity_type_code: { type: 'keyword' },
					},
				},
				demographic: {
					properties: {
						updated_datetime: { type: 'keyword' },
						created_datetime: { type: 'keyword' },
						gender: { type: 'keyword' },
						state: { type: 'keyword' },
						demographic_id: { type: 'keyword' },
						year_of_birth: { type: 'integer' },
						race: { type: 'keyword' },
						submitter_id: { type: 'keyword' },
						ethnicity: { type: 'keyword' },
						year_of_death: { type: 'keyword' },
					},
				},
				project: {
					properties: {
						project_id: { type: 'keyword' },
						disease_type: { type: 'keyword' },
						released: { type: 'boolean' },
						state: { type: 'keyword' },
						primary_site: { type: 'keyword' },
						name: { type: 'keyword' },
					},
				},
				summary: {
					properties: {
						data_categories: {
							type: 'nested',
							properties: {
								file_count: { type: 'integer' },
								data_category: { type: 'keyword' },
							},
						},
					},
				},
				observation: {
					type: 'nested',
					properties: {
						src_vcf_analysis_id: { type: 'keyword' },
						repository: { type: 'keyword' },
						platform: { type: 'keyword' },
						experimental_strategy: { type: 'keyword' },
						variant_caller: { type: 'keyword' },
						read_depth: {
							properties: {
								n_alt_count: { type: 'integer' },
								n_ref_count: { type: 'integer' },
								n_depth: { type: 'integer' },
								t_alt_count: { type: 'integer' },
								t_ref_count: { type: 'integer' },
								t_depth: { type: 'integer' },
							},
						},
						sample: {
							properties: {
								submitter_sample_id: { type: 'keyword' },
								matched_normal_submitter_sample_id: { type: 'keyword' },
								sample_type: { type: 'keyword' },
							},
						},
						specimen: {
							properties: {
								submitter_specimen_id: { type: 'keyword' },
								submitter_primary_diagnosis_id: { type: 'keyword' },
								specimen_acquisition_interval: { type: 'keyword' },
								specimen_anatomic_location: { type: 'keyword' },
								specimen_laterality: { type: 'keyword' },
								tumour_histological_type: { type: 'keyword' },
								pathological_tumour_staging_system: { type: 'keyword' },
								pathological_stage_group: { type: 'keyword' },
								tumour_grading_system: { type: 'keyword' },
								tumour_grade: { type: 'keyword' },
								percent_tumour_cells: { type: 'keyword' },
								specimen_tissue_source: { type: 'keyword' },
								specimen_type: { type: 'keyword' },
								tumour_normal_designation: { type: 'keyword' },
							},
						},
						workflow: {
							properties: {
								workflow_name: { type: 'keyword' },
								workflow_version: { type: 'keyword' },
								genome_build: { type: 'keyword' },
								inputs: {
									type: 'nested',
									properties: {
										analysis_type: { type: 'keyword' },
										tumour_analysis_id: { type: 'keyword' },
									},
								},
							},
						},
					},
				},
			},
		},
		gene: {
			type: 'nested',
			properties: {
				gene_chromosome: { type: 'keyword' },
				gene_start: { type: 'integer' },
				gene_end: { type: 'integer' },
				gene_strand: { type: 'integer' },
				symbol: { type: 'keyword' },
				name: { type: 'keyword' },
				synonyms: { type: 'keyword' },
				description: { type: 'keyword' },
				biotype: { type: 'keyword' },
				is_cancer_gene_census: { type: 'keyword' },
				ensembl_gene_id: { type: 'keyword' },
				cytoband: { type: 'keyword' },
				hgnc_gene_id: { type: 'keyword' },
				cosmic_gene_id: { type: 'keyword' },
				entrez_gene_id: { type: 'keyword' },
				omim_gene_id: { type: 'keyword' },
			},
		},
	},
} satisfies MappingTypeMapping;

export default mappings;
